language: ruby
sudo: false
rvm:
- 2.2
env:
  global:
  - domain: alpha.coderouge.co
  - site_path: "/var/www/arkos/site"
  - secure: wq4Ri5cRP98X68Ll8oSDivW1UBoZZRNussDG42BFf6RJbqbco1GoElOPASoRccXju7nO4fAs7ElYNLNim9DBNMwePso1XBottcDw4O8xoVZCpZzTbL2c7yg3NPSPagAJQdtTo7bIKZjpW3blTpSTlUouxWFiUlYUU3Pk+BSxNLgoV/9KbzfJpIhaYiYqS2JZ9UeApwCxW+KoInd7FVbf+gk9ZxjNgVC7mGwn0owJANUrSTpos0x1LxiCxyzy8FEahuKaQHZe6zhbq84Z5oxuuFwY0u5EhuRG1oweFlq11TDHqkLaNTvVIJr4tKCMgpd7NWN4YySZ0nLaP108wiBU0NLqa4zPFBfYVsoOaj5sbfL9TawGCJPxbPzghW5RkFfJLN2EyYEIDJOtPq9K1nuhDBQ+BG3EdSrwDU0pPSjsukeHuRgzLoxcJJBeOW2VbuCOlBXnyAv4G2U9zSdyBX+p1932C7c1JEE+3MxQ1AfuAH6hKknWHnffnJIKuwa0Fo24REtFL9yKzxLWRgBp9f4vEIAMlZPu9y7Y8VW8UjAPEmDaZxEskVzRtxDsQYY2An9YXKOcDXY/ZcdWdVuMBswM/76EaNWGOz/T9/j86m2MxI8KMQqy1eMP0iMBwu8lO1mTrk48FCdVgxB3tqIvbKFMS7psCW88+UUUJIidLoI5sy0=
script: bundle exec jekyll build
after_success:
- "./deploy/deploy.sh"
